/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClassSelectorDialog.java
 *
 * Created on 29-apr-2009, 18.33.27
 */
package org.easyway.ueditor2;

import java.util.ArrayList;
import java.util.List;
import org.easyway.ueditor2.forms.ClassSelectorPanel;

/**
 *
 * @author Daniele
 */
public class ClassSelectorDialog extends javax.swing.JDialog {

    ArrayList<ClassSelectorPanel> selectorPanelList;

    /** Creates new form ClassSelectorDialog */
    public ClassSelectorDialog(java.awt.Frame parent, List<Class> classList) {
        super(parent, true);
        initComponents();
        selectorPanelList = new ArrayList<ClassSelectorPanel>(classList.size());

        for (Class clazz : classList) {
            if (clazz.getSimpleName().equals("")) {
                continue;
            }
            ClassSelectorPanel panel = new ClassSelectorPanel(clazz);
            selectorPanelList.add(panel);
            innerPanel.add(panel);
        }

        innerPanel.validate();
        scrollPanel.repaint();
    }

    public ArrayList<Class> getSelectedClasses() {
        ArrayList<Class> outList = new ArrayList<Class>(selectorPanelList.size());
        for (ClassSelectorPanel panel : selectorPanelList) {
            Class selectedClazz = panel.getSelectedClass();
            if (selectedClazz != null) {
                outList.add(selectedClazz);
            }
        }
        return outList;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanel = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        innerPanel.setLayout(new java.awt.GridLayout(0, 1));
        scrollPanel.setViewportView(innerPanel);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addComponent(okButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
