/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on 3-apr-2009, 11.45.57
 */
package org.easyway.ueditor2;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.easyway.ueditor2.rightPanels.AutoUpdater;
import org.easyway.ueditor2.rightPanels.BeanEditor;
import org.easyway.ueditor2.rightPanels.Palette;
import org.easyway.ueditor2.system.OpenGLArea;

/**
 *
 * @author Daniele
 */
public class StartUEditor2 extends javax.swing.JFrame {

    AutoUpdater autoUpdater;
    EditorCore editorCore;

    /**
     * starts the UEditor2<br/>
     */
    public static void startUEditor2() {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StartUEditor2().setVisible(true);
            }
        });
    }

    public StartUEditor2() {
        this(-1, -1);
    }

    /** Creates new form MainFrame */
    public StartUEditor2(int width, int height) {
        //setUndecorated(true);
        // Get the size of the default screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        if (dim.getWidth() < 1024 || dim.getHeight() < 768) {
            JOptionPane.showMessageDialog(this, "Your Screen resolution can be too low!\nPlease increase it for a correct view of the UEditor!");
        }
        try {
            UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(StartUEditor2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(StartUEditor2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(StartUEditor2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(StartUEditor2.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        if (width <= 0) {
            width = getMaximumSize().width;
        }
        if (height <= 0) {
            height = getMaximumSize().height;
        }
        setSize(width, height);
        if ((float)getWidth()/(float)getHeight() >= 2) {
            setSize(getWidth()/2, getHeight());
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                System.out.println("MainFrame Width: " + getWidth() + " MainFrame Height: " + getHeight());
                editorCore = new EditorCore((int) getWidth(), (int) getHeight(), 32, openGLArea1.getCanvas(), StartUEditor2.this);
                palette1.beanEditor = beanEditor1;
                palette1.editorCore = editorCore;
                layersVisibility1.init();
                autoUpdater = new AutoUpdater(250, getBeanEditor());
                autoUpdater.start();

            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openGLArea1 = new org.easyway.ueditor2.system.OpenGLArea();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        outputPanel1 = new org.easyway.ueditor2.southPanels.OutputPanel();
        layersVisibility1 = new org.easyway.ueditor2.southPanels.miscellaneousPanel();
        tiledMapPanel1 = new org.easyway.ueditor2.tileEditor.TiledMapPanel();
        scripterPanel1 = new org.easyway.ueditor2.southPanels.ScripterPanel();
        editSelectedPanel1 = new org.easyway.ueditor2.southPanels.EditSelectedPanel();
        navigator1 = new org.easyway.ueditor2.southPanels.Navigator();
        RightTabbedPanel = new javax.swing.JTabbedPane();
        palette1 = new org.easyway.ueditor2.rightPanels.Palette();
        beanEditor1 = new org.easyway.ueditor2.rightPanels.BeanEditor();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New UEditor ");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.addTab("Output", outputPanel1);
        jTabbedPane1.addTab("miscellaneous", layersVisibility1);
        jTabbedPane1.addTab("Tiled Map", tiledMapPanel1);
        jTabbedPane1.addTab("Scripter", scripterPanel1);
        jTabbedPane1.addTab("Edit Selected", editSelectedPanel1);

        navigator1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navigator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addContainerGap())
        );

        RightTabbedPanel.addTab("Palette", palette1);
        RightTabbedPanel.addTab("Properties", beanEditor1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(openGLArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightTabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(openGLArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(RightTabbedPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public BeanEditor getBeanEditor() {
        return beanEditor1;
    }

    public Palette getPalette() {
        return palette1;
    }

    public JTabbedPane getRightTabbedPanel() {
        return RightTabbedPanel;
    }

    public OpenGLArea getGameArea() {
        return openGLArea1;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        startUEditor2();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane RightTabbedPanel;
    private org.easyway.ueditor2.rightPanels.BeanEditor beanEditor1;
    private org.easyway.ueditor2.southPanels.EditSelectedPanel editSelectedPanel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.easyway.ueditor2.southPanels.miscellaneousPanel layersVisibility1;
    private org.easyway.ueditor2.southPanels.Navigator navigator1;
    private org.easyway.ueditor2.system.OpenGLArea openGLArea1;
    private org.easyway.ueditor2.southPanels.OutputPanel outputPanel1;
    private org.easyway.ueditor2.rightPanels.Palette palette1;
    private org.easyway.ueditor2.southPanels.ScripterPanel scripterPanel1;
    private org.easyway.ueditor2.tileEditor.TiledMapPanel tiledMapPanel1;
    // End of variables declaration//GEN-END:variables
}
