/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CameraPropertiesDialog.java
 *
 * Created on 26-nov-2009, 0.51.36
 */
package org.easyway.ueditor2.southPanels;

import java.awt.Color;
import org.easyway.system.StaticRef;
import org.easyway.ueditor2.effects.Effect;

/**
 *
 * @author RemalKoil
 */
public class CameraPropertiesDialog extends javax.swing.JDialog {

    /** Creates new form CameraPropertiesDialog */
    public CameraPropertiesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Color bgColor = StaticRef.getCamera().getBackgroundColor();
        redBg.setValue(bgColor.getRed());
        greenBg.setValue(bgColor.getGreen());
        blueBg.setValue(bgColor.getBlue());
        updatePreviewColor();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        redBg = new javax.swing.JSpinner();
        greenBg = new javax.swing.JSpinner();
        blueBg = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        previewBgColor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Camera Properies Dialog");

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Background Color:");

        redBg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        redBg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                redBgStateChanged(evt);
            }
        });
        redBg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                redBgPropertyChange(evt);
            }
        });

        greenBg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        greenBg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                greenBgStateChanged(evt);
            }
        });

        blueBg.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));
        blueBg.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                blueBgStateChanged(evt);
            }
        });

        jLabel2.setText("Red");

        jLabel3.setText("Blue");

        jLabel4.setText("Green");

        previewBgColor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Preview Color", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout previewBgColorLayout = new javax.swing.GroupLayout(previewBgColor);
        previewBgColor.setLayout(previewBgColorLayout);
        previewBgColorLayout.setHorizontalGroup(
            previewBgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        previewBgColorLayout.setVerticalGroup(
            previewBgColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(204, 204, 204))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(redBg, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(greenBg, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(blueBg, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(previewBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previewBgColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(blueBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(greenBg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(okButton)
                            .addComponent(cancelButton))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        final int red = (Integer) redBg.getValue();
        final int green = (Integer) greenBg.getValue();
        final int blue = (Integer) blueBg.getValue();
        new Effect() {

            @Override
            public void create() {
                StaticRef.getCamera().setBackgroundColor(red, green, blue);
            }
        };
        dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void redBgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_redBgPropertyChange
        
    }//GEN-LAST:event_redBgPropertyChange

    private void redBgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_redBgStateChanged
        updatePreviewColor();
    }//GEN-LAST:event_redBgStateChanged

    private void greenBgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_greenBgStateChanged
        updatePreviewColor();
    }//GEN-LAST:event_greenBgStateChanged

    private void blueBgStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_blueBgStateChanged
        updatePreviewColor();
    }//GEN-LAST:event_blueBgStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updatePreviewColor() {
        final int red = (Integer) redBg.getValue();
        final int green = (Integer) greenBg.getValue();
        final int blue = (Integer) blueBg.getValue();
        previewBgColor.setBackground(new Color(red,green,blue));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                CameraPropertiesDialog dialog = new CameraPropertiesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner blueBg;
    private javax.swing.JButton cancelButton;
    private javax.swing.JSpinner greenBg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel previewBgColor;
    private javax.swing.JSpinner redBg;
    // End of variables declaration//GEN-END:variables
}
