/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LayersVisibility.java
 *
 * Created on 24-apr-2009, 10.52.07
 */
package org.easyway.ueditor2.southPanels;

import java.awt.List;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.easyway.debug.DebugManager;
import org.easyway.objects.sprites2D.sentry.Sentry;
import org.easyway.system.state.GameState;
import org.easyway.ueditor2.EditorCore;
import org.easyway.ueditor2.SelectObjectDialog;
import org.easyway.ueditor2.TextureManagerDialog;
import org.easyway.ueditor2.effects.Effect;
import org.easyway.ueditor2.effects.TestKeyboardLinstenerEffect;
import org.easyway.ueditor2.effects.test.EndTestEffect;
import org.easyway.ueditor2.effects.test.StartTestEffect;

/**
 *
 * @author Daniele
 */
public class miscellaneousPanel extends javax.swing.JPanel {

    /** Creates new form LayersVisibility */
    public miscellaneousPanel() {
        initComponents();
    }

    public List getLayers() {
        return layers;
    }

    public void init() {
        List layersList = getLayers();
        for (int i = 0; i < GameState.getCurrentGEState().getLayers().length; ++i) {
            //StaticRef.layers[i].setType(StaticRef.layers[i].getType() + "_" + i);
            layersList.add("LAYER_" + i);
            layersList.select(i);
        }
        showSentry.setSelected(Sentry.showSentryes);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        layers = new java.awt.List();
        showSentry = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        testGameButton = new javax.swing.JButton();
        saveGameButton = new javax.swing.JButton();
        loadGameButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        layers.setMultipleMode(true);
        layers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                layersItemStateChanged(evt);
            }
        });
        layers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                layersActionPerformed(evt);
            }
        });

        showSentry.setText("show Sentry");
        showSentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSentryActionPerformed(evt);
            }
        });

        jButton1.setText("Manage Texture");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, testGameButton, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jButton1, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Select Object");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, testGameButton, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jButton2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        testGameButton.setText("Test Game");
        testGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testGameButtonActionPerformed(evt);
            }
        });

        saveGameButton.setText("Save Game");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, testGameButton, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), saveGameButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        saveGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveGameButtonActionPerformed(evt);
            }
        });

        loadGameButton.setText("Load Game");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, testGameButton, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), loadGameButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        loadGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameButtonActionPerformed(evt);
            }
        });

        jButton3.setText("System.gc()");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layers, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(showSentry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(showSentry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(testGameButton)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(saveGameButton)
                    .addComponent(loadGameButton))
                .addGap(46, 46, 46))
            .addComponent(layers, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void layersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_layersItemStateChanged
        for (int i = 0; i < GameState.getCurrentGEState().getLayers().length; ++i) {
            EditorCore.showLayer[i] = layers.isIndexSelected(i);
        }
    }//GEN-LAST:event_layersItemStateChanged

    private void showSentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSentryActionPerformed
        Sentry.showSentryes = showSentry.isSelected();
    }//GEN-LAST:event_showSentryActionPerformed

    private void layersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_layersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_layersActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TextureManagerDialog tmd = new TextureManagerDialog(false);
        tmd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SelectObjectDialog so = new SelectObjectDialog();
        so.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void testGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testGameButtonActionPerformed
        testGameButton.setEnabled(false);
        if (DebugManager.debug) {
            JOptionPane.showMessageDialog(EditorCore.getMainFrame(), "You can stop the game test pressing: Left Ctrl + Right Shift + Q", "Test mode",JOptionPane.WARNING_MESSAGE);
            new StartTestEffect(testGameButton);
            new TestKeyboardLinstenerEffect(testGameButton);
            EditorCore.getMainFrame().getGameArea().gainFocus();
        } else {
            new EndTestEffect(testGameButton);
        }
}//GEN-LAST:event_testGameButtonActionPerformed

    private void loadGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameButtonActionPerformed

        JFileChooser fChooser = new JFileChooser();
        int returnVal = fChooser.showOpenDialog(EditorCore.getMainFrame());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            final File file = fChooser.getSelectedFile();
            if (file == null || !file.exists()) {
                return;
            }
            new Effect() {

                @Override
                public void create() {
                    EditorCore.getInstance().setSelected(null);
                    EditorCore.load(file.getAbsolutePath(), false);
                    DebugManager.debug = true;
                    destroy();
                }
            };
        }

    }//GEN-LAST:event_loadGameButtonActionPerformed

    private void saveGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveGameButtonActionPerformed
        JFileChooser fChooser = new JFileChooser();
        fChooser.setApproveButtonText("Save");

        int returnVal = fChooser.showOpenDialog(EditorCore.getMainFrame());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            final File file = fChooser.getSelectedFile();
            new Effect() {

                @Override
                public void create() {
                    EditorCore.getInstance().setSelected(null);
                    EditorCore.save(file.getAbsolutePath());
                    DebugManager.debug = true;
                    destroy();
                }
            };
        }
    }//GEN-LAST:event_saveGameButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.gc();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private java.awt.List layers;
    private javax.swing.JButton loadGameButton;
    private javax.swing.JButton saveGameButton;
    private javax.swing.JCheckBox showSentry;
    private javax.swing.JButton testGameButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
