/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptConsole.java
 *
 * Created on 28-set-2009, 13.11.41
 */

package org.easyway.debug;

import bsh.EasyWayInterpreter;

/**
 *
 * @author Daniele Paggi
 */
public class ScriptConsole extends javax.swing.JFrame {

    EasyWayInterpreter inter;

    /** Creates new form ScriptConsole */
    public ScriptConsole() {
        initComponents();
        inter = new EasyWayInterpreter(console);
        setVisible(true);
    }

    public void loop() {
        inter.run();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        console = new bsh.util.JConsole();
        weakUpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Script Console EasyWay 4");

        weakUpButton.setText("Weak Up Console");
        weakUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weakUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(weakUpButton)
                .addContainerGap())
            .addComponent(console, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(console, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weakUpButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weakUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weakUpButtonActionPerformed
        inter.weakUp();
    }//GEN-LAST:event_weakUpButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScriptConsole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bsh.util.JConsole console;
    private javax.swing.JButton weakUpButton;
    // End of variables declaration//GEN-END:variables

}
