/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewVEdtiro.java
 *
 * Created on 11-gen-2010, 9.45.22
 */
package org.easyway.vectorialEditor;

import java.awt.Color;
import java.awt.Graphics;
import org.easyway.geometry2D.Segment;
import org.lwjgl.util.vector.Vector3f;
import static org.easyway.vectorialEditor.Data.*;

/**
 *
 * @author RemalKoil
 */
public class PreviewVEditor extends javax.swing.JPanel {

    /** Creates new form PreviewVEdtiro */
    public PreviewVEditor() {
        initComponents();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        if (image != null) {
            g.drawImage(image, 0, 0, this);
        }
        for (Vector3f p : points) {
            g.setColor(Color.RED);
            int size = 5;
            g.fillOval((int) p.getX() - size / 2, (int) p.getY() - size / 2, size, size);
        }
        for (Segment s : segments) {
            Vector3f p = s.getPointAt(0.0f);
            Vector3f q = s.getPointAt(1.0f);
            g.drawLine((int) p.getX(), (int) p.getY(), (int) q.getX(), (int) q.getY());
        }
        if (selectedPoint != null) {
            g.setColor(Color.GREEN);
            int size = 8;
            g.fillOval((int) selectedPoint.getX() - size / 2, (int) selectedPoint.getY() - size / 2, size, size);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
