
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GPSettings.java
 *
 * Created on 15-feb-2010, 15.42.21
 */
/**
 *
 * @author Do$$e
 */
public class GPSettings extends javax.swing.JFrame {

    /** Creates new form GPSettings */
    public GPSettings() {
        initComponents();
        setSize(269, 232);
        setLocation(150,150);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbFire = new javax.swing.JComboBox();
        cmbRockets = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPause = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gamepad settings");
        setResizable(false);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setText("Fire/Click button");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 100, 30);

        jPanel1.add(cmbFire);
        cmbFire.setBounds(120, 30, 120, 30);

        jPanel1.add(cmbRockets);
        cmbRockets.setBounds(120, 70, 120, 30);

        jLabel3.setText("Rockets");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 100, 30);

        jLabel4.setText("Pause game");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 100, 30);

        jPanel1.add(cmbPause);
        cmbPause.setBounds(120, 110, 120, 30);

        jButton1.setText("Reset settings");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 150, 110, 30);

        jButton2.setText("Save settings");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 150, 110, 30);

        jButton3.setText("Exit without saving");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 190, 230, 30);

        jButton4.setFont(new java.awt.Font("Lucida Console", 0, 10));
        jButton4.setText("X");
        jButton4.setMaximumSize(new java.awt.Dimension(40, 20));
        jButton4.setMinimumSize(new java.awt.Dimension(40, 20));
        jButton4.setPreferredSize(new java.awt.Dimension(40, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(230, 0, 40, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loaderBar_Focused.png"))); // NOI18N
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 270, 20);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cmbFire.setSelectedIndex(0);
        cmbRockets.setSelectedIndex(1);
        cmbPause.setSelectedIndex(5);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (int i = 0; i <= 30; i++) {
            cmbFire.addItem("Button " + (i + 1));
            cmbRockets.addItem("Button " + (i + 1));
            cmbPause.addItem("Button " + (i + 1));
        }
        loadSettings();
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mygame.CommonVar.GPFire=cmbFire.getSelectedIndex();
        mygame.CommonVar.GPRockets=cmbRockets.getSelectedIndex();
        mygame.CommonVar.GPPause=cmbPause.getSelectedIndex();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        jLabel1.setIcon(new ImageIcon("images/loaderBar_UnFocused.png"));
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jLabel1.setIcon(new ImageIcon("images/loaderBar_Focused.png"));
    }//GEN-LAST:event_formWindowGainedFocus

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
         try {
            Point p = java.awt.MouseInfo.getPointerInfo().getLocation();
            //SwingUtilities.convertPointToScreen(p, this);
            setLocation(p.x - 135, p.y - 10);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jLabel1MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    NimRODTheme nt=new NimRODTheme();
                    nt.setPrimary1(new Color(255,24,24));
                    nt.setPrimary2(new Color(255,34,34));
                    nt.setPrimary3(new Color(255,44,44));
                    nt.setSecondary1(new Color(25,30,39));
                    nt.setSecondary2(new Color(35,40,49));
                    nt.setSecondary3(new Color(45,50,59));
                    nt.setWhite(new Color(73,72,84));
                    nt.setBlack(new Color(255,255,255));
                    nt.setMenuOpacity(195);
                    nt.setFrameOpacity(180);
                    NimRODLookAndFeel lef=new NimRODLookAndFeel();
                    lef.setCurrentTheme(nt);
                    UIManager.setLookAndFeel(lef);
                } catch (Exception ex) {
                    Logger.getLogger(GPSettings.class.getName()).log(Level.SEVERE, null, ex);
                }
                new GPSettings().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbFire;
    private javax.swing.JComboBox cmbPause;
    private javax.swing.JComboBox cmbRockets;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void loadSettings() {
        cmbFire.setSelectedIndex(mygame.CommonVar.GPFire);
        cmbRockets.setSelectedIndex(mygame.CommonVar.GPRockets);
        cmbPause.setSelectedIndex(mygame.CommonVar.GPPause);
    }
}
