
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.net.URI;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Updater.java
 *
 * Created on 1-apr-2010, 9.20.44
 */

/**
 *
 * @author Do$$e
 */
public class Updater extends javax.swing.JFrame {
    private static String version, address;
    /** Creates new form Updater */
    public Updater() {
        initComponents();
        setSize(210+(version.length()*5),115);
        setLocation(250,250);
        jLabel1.setText("A newer version is available: "+version);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("MissionX Updater");

        jLabel1.setText("A newer version is available: VERSION");

        jButton1.setText("Download now");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
        try {
            desktop.browse(new URI(address));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR!\n"+ex.getMessage(),"Browser error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        version=args[0];
        address=args[1];
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    //UIManager.setLookAndFeel("com.nilo.plaf.nimrod.NimRODLookAndFeel");
                    //UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
                    NimRODTheme nt = new NimRODTheme();
                    nt.setPrimary1(new Color(255, 24, 24));
                    nt.setPrimary2(new Color(255, 34, 34));
                    nt.setPrimary3(new Color(255, 44, 44));
                    nt.setSecondary1(new Color(25, 30, 39));
                    nt.setSecondary2(new Color(35, 40, 49));
                    nt.setSecondary3(new Color(45, 50, 59));
                    nt.setWhite(new Color(73, 72, 84));
                    nt.setBlack(new Color(255, 255, 255));
                    nt.setMenuOpacity(195);
                    nt.setFrameOpacity(180);
                    NimRODLookAndFeel lef = new NimRODLookAndFeel();
                    lef.setCurrentTheme(nt);
                    UIManager.setLookAndFeel(lef);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(new JOptionPane(), "Warning: Couldn't set LookAndFeel. This app will look bad, but the game won't be compromised.", "NimROD Error", JOptionPane.ERROR_MESSAGE);
                }
                new Updater().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
