/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TexturePreview.java
 *
 * Created on 24-apr-2009, 13.32.23
 */
package org.easyway.ueditor2.forms;

import java.awt.Graphics;
import java.awt.Image;
import org.easyway.interfaces.base.ITexture;

/**
 *
 * @author Daniele
 */
public class TexturePreview extends javax.swing.JPanel {

    private static final long serialVersionUID = -2805538372186488757L;
    ITexture texture;
    Image image;

    /** Creates new form TexturePreview */
    public TexturePreview() {
        initComponents();
    }

    public void setImage(Image image, ITexture texture) {
        this.image = image;
        this.texture = texture;
        repaint();
    }

    public Image getImage() {
        return image;
    }

    @Override
    public void paint(Graphics g) {

        super.paint(g);
        if (image != null) {
            int width = image.getWidth(this) < getWidth() ? image.getWidth(this) : getWidth();
            int height = image.getHeight(this) < getHeight() ? image.getHeight(this) : getHeight();

            g.drawImage(image, 0, 0, width, height, (int) (texture.getXStart() * texture.getWidthHW()), (int) (texture.getYStart() * texture.getHeightHW()),
                    (int) (texture.getXEnd() * texture.getWidthHW()), (int) (texture.getYEnd() * texture.getHeightHW()), this);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(256, 256));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
